#!/bin/bash

while true; do
clear

cat << "EOF"
████████╗██████╗ ██╗███████╗███████╗██████╗ 
╚══██╔══╝██╔══██╗██║╚══███╔╝██╔════╝██╔══██╗
   ██║   ██████╔╝██║  ███╔╝ █████╗  ██████╔╝
   ██║   ██╔══██╗██║ ███╔╝  ██╔══╝  ██╔══██╗
   ██║   ██║  ██║██║███████╗███████╗██║  ██║
   ╚═╝   ╚═╝  ╚═╝╚═╝╚══════╝╚══════╝╚═╝  ╚═╝
EOF

echo ""
echo "1) Install Cloudflare"
echo "2) Uninstall Cloudflare"
echo "3) Exit"
echo ""
read -p "Select option [1-3]: " opt

case $opt in
  1)
    # Add cloudflare gpg key
    sudo mkdir -p --mode=0755 /usr/share/keyrings
    curl -fsSL https://pkg.cloudflare.com/cloudflare-public-v2.gpg | sudo tee /usr/share/keyrings/cloudflare-public-v2.gpg >/dev/null

    # Add this repo to your apt repositories
    echo 'deb [signed-by=/usr/share/keyrings/cloudflare-public-v2.gpg] https://pkg.cloudflare.com/cloudflared any main' | sudo tee /etc/apt/sources.list.d/cloudflared.list

    # install cloudflared
    sudo apt-get update && sudo apt-get install cloudflared
    ;;
  2)
    sudo cloudflared service uninstall
    exit 0
    ;;
  3)
    exit 0
    ;;
  *)
    echo "❌ Invalid Option"
    sleep 1
    ;;
esac
done
