#!/bin/bash

while true; do
clear

cat << "EOF"
████████╗██████╗ ██╗███████╗███████╗██████╗ 
╚══██╔══╝██╔══██╗██║╚══███╔╝██╔════╝██╔══██╗
   ██║   ██████╔╝██║  ███╔╝ █████╗  ██████╔╝
   ██║   ██╔══██╗██║ ███╔╝  ██╔══╝  ██╔══██╗
   ██║   ██║  ██║██║███████╗███████╗██║  ██║
   ╚═╝   ╚═╝  ╚═╝╚═╝╚══════╝╚══════╝╚═╝  ╚═╝
EOF

echo ""
echo "1) Install Tailscale"
echo "2) Uninstall Tailscale"
echo "3) Exit"
echo ""
read -p "Select option [1-3]: " opt

case $opt in
  1)
    curl -fsSL https://tailscale.com/install.sh | sh
    sudo apt install systemctl
    sudo systemctl start tailscale
    sudo tailscale up
    ;;
  2)
    sudo apt-get remove tailscale
    ;;
  3)
    exit 0
    ;;
  *)
    echo "❌ Invalid Option"
    sleep 1
    ;;
esac
done
