#!/bin/bash

while true; do
clear

cat << "EOF"
████████╗██████╗ ██╗███████╗███████╗██████╗ 
╚══██╔══╝██╔══██╗██║╚══███╔╝██╔════╝██╔══██╗
   ██║   ██████╔╝██║  ███╔╝ █████╗  ██████╔╝
   ██║   ██╔══██╗██║ ███╔╝  ██╔══╝  ██╔══██╗
   ██║   ██║  ██║██║███████╗███████╗██║  ██║
   ╚═╝   ╚═╝  ╚═╝╚═╝╚══════╝╚══════╝╚═╝  ╚═╝
EOF

echo ""
echo "1) Install Vps Bot"
echo "2) Exit"
echo ""
read -p "Select option [1-3]: " opt

case $opt in
  1)
    apt install python3-pip -y
    mkdir -p ~/.config/pip && echo -e "[global]\nbreak-system-packages = true" > ~/.config/pip/pip.conf
    apt install git -y
    git clone https://github.com/Trizer540/config.git
    ;;
  2)
    exit 0
    ;;
  *)
    echo "❌ Invalid Option"
    sleep 1
    ;;
esac
done
